### ISSUE TITLE
Code review for the Full Stack open course

### ISSUE THREAD

**Issue by Kaltsoon** [SubroBlack/RatingApp#5]
# Code review

Hi @SubroBlack! Here's a short code review for your Full Stack course project. 

### What did I do?

Unfortunately, I couldn't do mutch because I wasn't able to loging using the README's credentials or joining a new user using the README's AdminPin.

### Experience

- Logging in doesn't work using the credentilas in the README (username: test, password: test). The server responds with a 401 status code
- Logging in with invalid credentials shows error message "Error: Request failed with status code 401". This messages if not very user-friendly, probably 90% of users would have no idea what status code 401 is. In addition it would be nice to remain in the login form instead of a redirect to front page
- Joining with the AdminPin in the README causes an internal server error (with status code 500)

## Code

- The front-end code is well organized, great work!
- Consider using `const` type variables for storing action types instead of using [hard coded strings](https://github.com/SubroBlack/RatingApp/blob/master/Front/src/reducers/items.js#L21). This minimizes the risk of bugs caused by typos and eases refactoring. Redux's documentation has great [instructions](https://redux.js.org/basics/actions) regarding this
- You should use [action creators](https://redux.js.org/basics/actions#action-creators) instead of [plain objects](https://github.com/SubroBlack/RatingApp/blob/master/Front/src/reducers/items.js#L20) when dispatching actions. When you abstract the creation of the action with an action creator it is much easier to change the underlying structure and logic later without a need of major refactoring.
- [Redux Toolkit](https://redux-toolkit.js.org/) has great functionality for reducing Redux boilerplate code and for example making immutable state updates much easier
- API requests have good service abstractions, such as [items.js](https://github.com/SubroBlack/RatingApp/blob/master/Front/src/services/items.js). Well done!
- A form state management library such as [Formik](https://formik.org) makes it easier to handle the state of larger forms
- [Here](https://github.com/SubroBlack/RatingApp/blob/master/Front/src/components/AppMenu.js#L62) you should use React Router's `Link` component instead
- Why is the both `yarn.lock` and `package-lock.json` file in the [front-end](https://github.com/SubroBlack/RatingApp/tree/master/Front)? You should use either npm or Yarn.
- The back-end code is also well organized, nicely done!
- Calling the [toJSON](https://github.com/SubroBlack/RatingApp/blob/master/controllers/items.js#L37) methods explicitly isn't necessary. `res.send` and `res.json` methods will call them automatically when they serialize the JSON response
- You should avoid so called [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) like [this](https://github.com/SubroBlack/RatingApp/blob/master/controllers/items.js#L38) and [this](https://github.com/SubroBlack/RatingApp/blob/master/controllers/items.js#L36). Instead implement methods such as `user.hasAdminRole` and `user.hasUserRole` for the [User](https://github.com/SubroBlack/RatingApp/blob/master/models/user.js) model

## Summary

The project's idea sounds very useful, even if I had issues with joining and logging in. This forced me to focus more on the application's code, which is totally fine. The code is well organized both in the back-end an in the front-end. The quality of code is pretty good, it is fairly easy to read and understand. There are also good abstractions, such as the API request abstractions. However, minor refactoring would improve the code's quality and maintainability.

All in all, good work!

**Comment by SubroBlack** [comment]
### Fixed Issues
I have tried to fix some issues raised by you. I will continue to fix the rest of the issues as well. 
- First, in the login credentials, username was Test instead of test, but I have edited it so that name: test and password: test works.
- I have used const variables for Action Type instead of plain strings
- Also action creators are used instead of plain objects
- I have used Link in header and it will be implemented wherever applicable
- Yarn has been removed from Front
